{ pkgs, ... }:

{
  imports = [ ./hardware-configuration.nix ]; # :: Generated by the installer later

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  networking.hostName = "nixos-dev";
  networking.networkmanager.enable = true;

  time.timeZone = "Asia/Manila";

  # :: Fish is essential for your workflow
  programs.fish.enable = true;
  users.defaultUserShell = pkgs.fish;

  # :: Enable Niri (or swap for Sway)
  programs.niri.enable = true;

  users.users.dubi = { # :: Change 'yourusername'
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" ];
  };

  environment.systemPackages = with pkgs; [
    git
    curl
    wget
  ];

  system.stateVersion = "24.11";
}
