[accessibility]
ui_scale = 0.90000000000000002

[audio]
enable_sounds = true
sound_volume = 0.5

[bar]
order = [ "default" ]

    [bar.default]
    background_opacity = 0.0
    capsule = true
    capsule_opacity = 0.76000000000000001
    capsule_padding = 11.0
    center = [ "clock", "media" ]
    end = [ "network", "bar", "volume", "battery", "tray", "notifications", "control-center" ]
    font_family = "FiraCode Nerd Font"
    margin_edge = 4
    margin_ends = 16
    scale = 0.80000000447034836
    shadow = false
    start = [ "group:g1", "workspaces" ]
    widget_spacing = 6

        [[bar.default.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "cpu", "ram", "temp", "disk_used" ]
        opacity = 0.75999999046325684
        padding = 11.0

[battery]
warning_threshold = 20

[control_center.calendar]
show_events_card = false

[dock]
enabled = false
shadow = false

[idle]
behavior_order = [ "dim", "lock", "lock-and-suspend", "screen-off" ]
pre_action_fade_seconds = 5.0

    [idle.behavior.dim]
    action = "custom"
    command = "/home/thanmatt/.config/sway/scripts/panel-dim.sh dim"
    enabled = false
    resume_command = "/home/thanmatt/.config/sway/scripts/panel-dim.sh restore"
    timeout = 5.0

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 525.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 1800.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 500.0

[location]
address = "Manila, Philippines"
auto_locate = false

[lockscreen]
blur_intensity = 0.68000000000000005
tint_intensity = 0.0
wallpaper = "/home/thanmatt/Pictures/wallpapers/my-neighbor-totoro-sunflowers.png"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@WAYLAND-1",
    "lockscreen-login-box@DP-1",
    "lockscreen-widget-0000000000000004",
    "lockscreen-widget-0000000000000005",
    "lockscreen-widget-0000000000000003"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 1280.0
    cy = 781.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.0
        background_radius = 0.0
        center_password_text = true
        input_opacity = 0.31
        input_radius = 13.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = false
        show_media = false
        show_session_buttons = false
        show_unlock_hint = false
        show_weather = false

    [lockscreen_widgets.widget."lockscreen-login-box@WAYLAND-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 320.0
    cy = 178.0
    output = "WAYLAND-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@WAYLAND-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 384.0
    box_width = 880.0
    cx = 1280.0
    cy = 720.0
    output = "DP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        center_text = true
        clock_style = "digital"
        color = "on_surface"
        format = "{:%H}\\n{:%M}"
        shadow = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 48.0
    box_width = 176.0
    cx = 1280.0
    cy = 680.0
    output = "DP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = false
        background_opacity = 0.57000000000000006
        format = "{:%A}, {:%d} {:%b} {:%y}"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    box_height = 112.0
    box_width = 160.0
    cx = 1280.0
    cy = 494.5
    output = "DP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000004.settings]
        background = false
        format = "{:%H}"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000005]
    box_height = 112.0
    box_width = 160.0
    cx = 1280.0
    cy = 592.0
    output = "DP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000005.settings]
        background = false
        format = "{:%M}"

[nightlight]
enabled = true
temperature_day = 6500
temperature_night = 2700

[notification]
background_opacity = 1.0
layer = "overlay"
position = "top_right"

[osd]
background_opacity = 1.0
position = "top_right"
position_vertical = "top_right"

[plugin_settings."alexander/mimir"]
api_endpoint = "http://localhost:11434/v1"

[plugins]
enabled = [ "felipeartur/ai-usagebar", "alexander/mimir" ]

[shell]
font_family = "FiraCode Nerd Font"

    [shell.animation]
    enabled = true
    speed = 1.5000000223517418

    [shell.launcher]
    categories = false
    compact = true
    sort_by_usage = false

        [shell.launcher.providers.windows]
        global = true

    [shell.panel]
    open_near_click_control_center = true

[theme]
builtin = "Gruvbox"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "sway" ]
    community_ids = [ "discord" ]

[wallpaper]
directory = "/home/thanmatt/Pictures/wallpapers"
edge_smoothness = 0.050000000000000003
fill_color = "#1a1a2e"
fill_mode = "crop"
transition = [ "honeycomb" ]
transition_duration = 1500.0
transition_on_startup = true

    [wallpaper.automation]
    enabled = false
    interval_seconds = 300
    order = "random"

    [wallpaper.default]
    path = "/home/thanmatt/Pictures/wallpapers/my-neighbor-totoro-sunflowers.png"

    [wallpaper.last]
    path = "/home/thanmatt/Pictures/wallpapers/my-neighbor-totoro-sunflowers.png"

    [wallpaper.monitors.DP-1]
    path = "/home/thanmatt/Pictures/wallpapers/my-neighbor-totoro-sunflowers.png"

[weather]
enabled = true

[widget.bar]
scale = 1.2
type = "felipeartur/ai-usagebar:bar"
vendor = "anthropic"

[widget.clock]
format = "{:%H:%M:%S %p %a, %b %d, %Y}"
tooltip_format = "{:%A, %B %d, %Y}"
type = "clock"

[widget.control-center]
glyph = "send"

[widget.cpu]
display = "text"

[widget.disk_used]
display = "text"
stat = "disk_used_pct"
type = "sysmon"

[widget.media]
album_art_only = true
hide_when_no_media = true

[widget.network]
show_label = false

[widget.ram]
display = "text"

[widget.temp]
display = "text"

[widget.tray]
detached_panel = true
drawer = true
drawer_item_size = 24.0
type = "tray"

[widget.workspaces]
labels_only_when_occupied = true
max_label_chars = 2
pill_scale = 0.59999999999999998
style = "minimal"
type = "workspaces"
